#!/usr/bin/env python3
"""Generate allocation-free ECMAScript case equivalence tables from pinned UCD.

No runtime dependency on Python, its Unicode version, locale, or source files.
--check verifies provenance, all code points, and the exact generated artifact.
"""
import argparse
import collections
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / 'third_party/unicode/17.0.0'


def fields(name):
    for line in (DATA / name).read_text().splitlines():
        line = line.split('#', 1)[0].strip()
        if line:
            yield [f.strip() for f in line.split(';')]


def mappings():
    receipt = json.loads((DATA / 'receipt.json').read_text())
    assert receipt['unicode_version'] == '17.0.0'
    for f in receipt['files']:
        data = (DATA / f['path']).read_bytes()
        assert len(data) == f['bytes']
        assert hashlib.sha256(data).hexdigest() == f['sha256'], f['path']
    unicode = {}
    for f in fields('CaseFolding.txt'):
        if f[1] in ('C', 'S'):
            target = f[2].split()
            assert len(target) == 1
            unicode[int(f[0], 16)] = int(target[0], 16)
    upper = {int(f[0], 16): [int(f[12], 16)] for f in fields('UnicodeData.txt') if f[12]}
    for f in fields('SpecialCasing.txt'):
        if not f[4]:  # Default conversion, excluding locale/context tailoring.
            upper[int(f[0], 16)] = [int(c, 16) for c in f[3].split()]
    legacy = {c: to[0] for c, to in upper.items()
              if c <= 0xffff and len(to) == 1 and to[0] <= 0xffff
              and not (c >= 128 and to[0] < 128) and c != to[0]}
    return [('UNICODE', unicode, 0x110000), ('LEGACY', legacy, 0x10000)]


def rings(mapping):
    classes = collections.defaultdict(set)
    for c, canonical in mapping.items():
        assert mapping.get(canonical, canonical) == canonical
        classes[canonical].update((c, canonical))
    out = {}
    for members in classes.values():
        members = sorted(members)
        assert 1 < len(members) <= 4
        for i, c in enumerate(members):
            out[c] = members[(i + 1) % len(members)]
    return out


def compress(ring):
    # Contiguous ranges with one delta per parity compress alternating cased
    # alphabets as well as constant-offset blocks. No overlapping ranges.
    keys = sorted(ring)
    runs = []
    i = 0
    while i < len(keys):
        lo = hi = keys[i]
        deltas = [ring[lo] - lo] * 2
        i += 1
        if i < len(keys) and keys[i] == hi + 1:
            hi = keys[i]
            deltas[1] = ring[hi] - hi
            i += 1
        while i < len(keys) and keys[i] == hi + 1 and ring[keys[i]] - keys[i] == deltas[(keys[i] - lo) % 2]:
            hi = keys[i]
            i += 1
        runs.append((lo, hi, *deltas))
    return runs


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    output = ['// Generated by tools/generate-casefold.py; do not edit.',
              '// Unicode 17.0.0. Derived data under Unicode License V3;',
              '// see third_party/unicode/17.0.0/{LICENSE.txt,receipt.json}.',
              '// Rows: inclusive start/end, next-equivalent delta by offset parity.',
              '#[rustfmt::skip]']
    report = {}
    for name, mapping, limit in mappings():
        ring = rings(mapping)
        runs = compress(ring)
        # Exhaustively reconstruct the compressed representation, including
        # unassigned code points and surrogate values, against the source map.
        j = 0
        for c in range(limit):
            while j < len(runs) and runs[j][1] < c:
                j += 1
            actual = c
            if j < len(runs) and runs[j][0] <= c:
                row = runs[j]
                actual += row[2 + (c - row[0]) % 2]
            assert actual == ring.get(c, c), (name, c)
            expected = mapping.get(c, c)
            seen = set()
            item = c
            while item not in seen:
                seen.add(item)
                assert mapping.get(item, item) == expected
                item = ring.get(item, item)
            assert item == c and len(seen) <= 4
        output.append(f'pub(super) static {name}: &[[i32; 4]] = &[')
        output += [f'    [0x{lo:x}, 0x{hi:x}, {a}, {b}],' for lo, hi, a, b in runs]
        output += ['];', '#[rustfmt::skip]']
        report[name.lower()] = dict(mapped=len(mapping), ring_members=len(ring), ranges=len(runs), bytes=len(runs)*16, checked=limit)
    output.pop()
    text = '\n'.join(output) + '\n'
    dest = ROOT / 'src/casefold_data.rs'
    if args.check:
        assert dest.read_text() == text, 'generated output changed'
    else:
        dest.write_text(text)
    print(json.dumps(report, indent=2))


if __name__ == '__main__':
    main()
